---
# Author: B M Krishna Reddy Kolli
# extra_vars input example
# ---
#Tasks:
#- ApplicationName: sample
#  Type: MaintanenceMode | PreTask | Patch | PostTask | Validation
#  Limit: svr12,svr34,svr56
#  StartTime: '00:15'
#  EndTime: '00:45'
#  Action: Place in MM | Stop Service | Install Patch | Start Service | App Check
#  Attributes: NULL | servicenames separated by comma
#  Wait: true | false
#  ChangeNo: ch0081762

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Pass inputs to validator taskwise
      include_role:
        name: input-validator-role-caller
      vars:
        app_name: "{{ item.ApplicationName }}"
        task_type: "{{ item.Type }}"
        affected_hosts: "{{ item.Limit }}"
        start_time: "{{ item.StartTime }}"
        end_time: "{{ item.EndTime }}"
        task_action: "{{ item.Action }}"
        action_attributes: "{{ item.Attributes }}"
        task_wait: "{{ item.Wait }}"
        change_no: "{{ item.ChangeNo }}"
      with_items: "{{ Tasks }}"
      ignore_errors: true