---
# Validate Inputs and call respective roles
- debug: 
    msg: "{{ app_name }} , {{ task_type }} , {{ affected_hosts }} , {{ start_time }} , {{ end_time }} , {{ task_action }} , {{ action_attributes }} , {{ task_wait }}"
